project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Polars"
  author: "Your Name"
  date: "last-modified"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true
    toc: true

bibliography: references.bib